### PR TITLE
actor shown on click, tiny hidden, actor mimics tiny, hide on return

### PR DESCRIPTION
**Pull request by troutcolor**
Just an idea, click on the big text to show the input. 

in action
http://git.johnj.info/bigify/

### CODE REVIEW

**Comment by cogdog** [comment]
Like it a lot, but does not wrap right on long strings. You have CSS

`#actor { #text-wrap:break;}`

seems to work better with

`#actor { #word-wrap:break-word;}`

**Comment by troutcolor** [comment]
I just fixed that (break-word ) and changed to a textarea to handle more lines than an input.

**Comment by cogdog** [comment]
Brilliant, thanks John. Putting it to use tomorrow.

**Comment by troutcolor** [comment]
Thank you, great to get a chance to try a pull and increase my git knowledge a wee bit:-)

**Pull request merged**
